services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Chatbot-Twilio-Bpi
    ports:
      - "7008:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
