// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace chatBotTwilio.Migrations
{
    [DbContext(typeof(DbSmpContext))]
    partial class DbSmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("Consortium")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("consortium");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("name");

                    b.Property<string>("NameShort")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nameshort");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("picture");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasColumnName("rfc");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("id_state");

                    b.HasKey("Id");

                    b.ToTable("providers");
                });

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<decimal>("AmountDll")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amountdll");

                    b.Property<decimal>("AmountMx")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amountmx");

                    b.Property<int?>("Consecutive")
                        .HasColumnType("int")
                        .HasColumnName("consecutive");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("date")
                        .HasColumnName("dateend");

                    b.Property<DateTime?>("DateStar")
                        .HasColumnType("date")
                        .HasColumnName("datestar");

                    b.Property<string>("DescripSmall")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripsmall");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("IdProvider")
                        .HasColumnType("int")
                        .HasColumnName("id_provider");

                    b.Property<string>("NumberContract")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contract");

                    b.Property<string>("Resident")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("resident");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("speciality");

                    b.Property<string>("StateContract")
                        .HasColumnType("varchar(40)")
                        .HasColumnName("statecontract");

                    b.Property<string>("Supervisor")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("supervisor");

                    b.Property<int>("Term")
                        .HasColumnType("int")
                        .HasColumnName("term");

                    b.Property<int>("id_provider")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProvider");

                    b.ToTable("contracts", t =>
                        {
                            t.Property("id_provider")
                                .HasColumnName("id_provider1");
                        });
                });

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Logbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("chatid");

                    b.Property<string>("Cuadrilla")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cuadrilla");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<TimeSpan?>("End")
                        .HasColumnType("time(7)")
                        .HasColumnName("end");

                    b.Property<int?>("FuelQuantity")
                        .HasColumnType("int")
                        .HasColumnName("fuel_quantity");

                    b.Property<int?>("IdOt")
                        .HasColumnType("int")
                        .HasColumnName("id_ot");

                    b.Property<int?>("IdProject")
                        .HasColumnType("int")
                        .HasColumnName("id_project");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    b.Property<int?>("IdResource")
                        .HasColumnType("int")
                        .HasColumnName("id_resource");

                    b.Property<string>("ImageAzure")
                        .HasColumnType("varchar(320)")
                        .HasColumnName("imageazure");

                    b.Property<string>("ImageReal")
                        .HasColumnType("varchar(320)")
                        .HasColumnName("imageReal");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasColumnName("image");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<int?>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("position");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReportDate")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("report_date");

                    b.Property<int?>("ReportSectionId")
                        .HasColumnType("int")
                        .HasColumnName("report_section_id");

                    b.Property<TimeSpan?>("Start")
                        .HasColumnType("time(7)")
                        .HasColumnName("start");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("supervisor");

                    b.Property<string>("TaskReference")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_reference");

                    b.Property<TimeSpan?>("Timexnote")
                        .HasColumnType("time(7)")
                        .HasColumnName("timexnote");

                    b.Property<string>("TypeNote")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasColumnName("typenote");

                    b.HasKey("Id");

                    b.ToTable("logbook");
                });

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Oilfield", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("id_contract");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("coordinates");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("oilfields");
                });

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<string>("BudgetManagement")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("budgetmanagement");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("classification");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("DateDelivery")
                        .HasColumnType("date")
                        .HasColumnName("datedelivery");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Diameter")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("diameter");

                    b.Property<string>("Government")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("government");

                    b.Property<int?>("IdActive")
                        .HasColumnType("int")
                        .HasColumnName("id_active");

                    b.Property<int?>("IdConsecutivo")
                        .HasColumnType("int")
                        .HasColumnName("idConsecutivo");

                    b.Property<int?>("IdContrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<int?>("IdOilfield")
                        .HasColumnType("int")
                        .HasColumnName("id_oilfield");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(14, 2)")
                        .HasColumnName("length");

                    b.Property<string>("LineRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("linerigth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ProgramEnd")
                        .HasColumnType("date")
                        .HasColumnName("programend");

                    b.Property<DateTime?>("ProgramStart")
                        .HasColumnType("date")
                        .HasColumnName("programstart");

                    b.Property<DateTime?>("RealPronosticLPO")
                        .HasColumnType("date")
                        .HasColumnName("realpronosticLPO");

                    b.Property<DateTime?>("RealPronosticTTT")
                        .HasColumnType("date")
                        .HasColumnName("realpronosticTTT");

                    b.Property<string>("ReceivedEngineering")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("receivedenginnering");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("state");

                    b.Property<string>("SupplyPipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("supplypipe");

                    b.Property<string>("TypeConstruction")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasColumnName("typeconstruction");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("year");

                    b.Property<int>("id_contract")
                        .HasColumnType("int");

                    b.Property<int>("id_oilfield")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato");

                    b.HasIndex("IdOilfield");

                    b.ToTable("projects", t =>
                        {
                            t.Property("id_oilfield")
                                .HasColumnName("id_oilfield1");
                        });
                });

            modelBuilder.Entity("chatBotTwilio.Models.WhatsApp.ConversationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentContract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentNoteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentProjectId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcorta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastInteraction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectPhotoInfoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConversationStates");
                });

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Contract", b =>
                {
                    b.HasOne("chatBotTwilio.Models.BPI.Company", "NavProvider")
                        .WithMany()
                        .HasForeignKey("IdProvider");

                    b.Navigation("NavProvider");
                });

            modelBuilder.Entity("chatBotTwilio.Models.BPI.Project", b =>
                {
                    b.HasOne("chatBotTwilio.Models.BPI.Contract", "NavContract")
                        .WithMany()
                        .HasForeignKey("IdContrato");

                    b.HasOne("chatBotTwilio.Models.BPI.Oilfield", "NavOilfield")
                        .WithMany()
                        .HasForeignKey("IdOilfield");

                    b.Navigation("NavContract");

                    b.Navigation("NavOilfield");
                });
#pragma warning restore 612, 618
        }
    }
}
